[package]
name = "valuelens"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.9"
serde_json = "1"
regex = "1"
walkdir = "2"
globset = "0.4"
pathdiff = "0.2"
chrono = { version = "0.4", features = ["serde"] }
valuelens-core = { path = "../valuelens-core" }
